### ISSUE TITLE
请问可否在设置程序中新增一个1280*960的分辨率？

### ISSUE THREAD

**Issue by TheoShira** [peaceshi/Wind4#1]
虽然说可以通过修改注册表解决，但在设置中有新增分辨率会更方便

**Comment by peaceshi** [comment]
理论上可行,但是实际会引入一些问题.
并不是设置了分辨率,程序就会按照指定分辨率正常运行.

正确的方法是枚举设备分辨率.只给出此设备在窗口/全屏模式支持的分辨率列表(没错,这两种情况支持的分辨率可能是不一样的).

也可以在用户选择自定义分辨率时,提醒用户这是危险行为,可能造成严重错误甚至损害你的硬件.
由于无法保证用户会输入哪些内容(比如1280写成12800), 产生不可预期的问题,还需要指定最低数值,最高数值和默认数值.

两种方法各有取舍.

**Comment by TheoShira** [comment]
指定数值应该就可以，目前我都是自行修改注册表，然后在配合dgVoodoo的16倍抗锯齿玩的

**Comment by peaceshi** [comment]
> 指定数值应该就可以，目前我都是自行修改注册表，然后在配合dgVoodoo的16倍抗锯齿玩的

确实应该这样 这样也可以保证手动设定了指定分辨率以外的值可以被程序正确读取.

**Comment by peaceshi** [comment]
风色幻想3已经添加该功能. 风色幻想4将在 V3.0 重构结束更新.

**Comment by peaceshi** [comment]
已更新
程序主体已完成.等待正式发布
可从此处提前体验.
https://github.com/peaceshi/WindConfig/suites/8759788131/artifacts/397052578

**Comment by peaceshi** [comment]
https://github.com/peaceshi/WindConfig/releases/tag/v3.0.0
